filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

logging.level: debug

#filebeat.autodiscover:
#  providers:
#    - type: docker
#      hints.enabled: true

    #processors:
  #- add_cloud_metadata: ~

filebeat.inputs:
  - type: log
    paths:
      - /var/log/wixit-auth/spring-boot-logger.log
    multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
    multiline.negate: true
    multiline.match: after


output.logstash:
  hosts: ["logstash:5044"]