server:
  port: 8080
spring:
  application:
    name: wixitAuth

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

logging:
  level:
    ROOT: INFO