version: 0.2
phases:
  pre_build:
    commands:
    - $(aws ecr get-login --no-include-email)
    - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
    - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
  build:
    commands:
    - echo mvn install
    - mvn install dockerfile:build
    - echo docker build
    - docker build --build-arg JAR_FILE=target/gs-spring-boot-docker-0.1.0.jar --build-arg CONFIG_FILE=externalConfigTemplate.yml --tag "$IMAGE_URI" .
  post_build:
    commands:
    - docker push "$IMAGE_URI"
    - printf '[{"name":"simple-app","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  files: images.json